# この設定ファイルは Rubocop のルールをカスタマイズします
AllCops:
  TargetRubyVersion: 3.0 # 使用している Ruby のバージョンを記載してください

Layout/IndentationWidth:
  EnforcedStyle: spaces # スペースを使用してインデントを整える
  Width: 2 # インデントの幅を2スペースに設定

Layout/IndentationStyle:
  EnforcedStyle: spaces # インデントをスペースに強制する

Lint/MissingCopEnableDirective:
  Enabled: false # 無効化を正確に指摘するルール (デフォルトでは無効可)
